# Generated by Django 4.1.4 on 2022-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0004_publickeys_eventsymkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickeys',
            name='signed_key',
            field=models.CharField(default='no data', max_length=500),
            preserve_default=False,
        ),
    ]
