# Generated by Django 4.1.4 on 2023-01-02 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendaApp', '0005_publickeys_signed_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsNewDev',
            fields=[
                ('ip_address', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('browser', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('public_key', models.CharField(max_length=500)),
                ('private_key_usr', models.CharField(default='null', max_length=500)),
                ('dest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_dev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
