# Generated by Django 4.1.4 on 2023-01-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0006_requestsnewdev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnewdev',
            name='public_key',
            field=models.CharField(default='null', max_length=500, null=True),
        ),
    ]
