# Generated by Django 4.1.4 on 2023-01-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0007_alter_requestsnewdev_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sign', to='agendaApp.event')),
            ],
        ),
    ]
