# Generated by Django 4.1.4 on 2023-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0008_eventsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIPs',
            fields=[
                ('ip_address', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('permanent', models.BooleanField(default=False)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
    ]
