# Generated by Django 4.1.4 on 2023-01-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0009_blockips'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsnewdev',
            name='salt_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
