# Generated by Django 4.1.4 on 2023-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0011_publickeys_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(max_length=500),
        ),
    ]
